# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Leonardo Thozo
tagline:             'Cloud Architect'
description:         'Um blog pessoal para falar de nuvems'
url:                 lthozo.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Leonardo Thozo
  url:               https://twitter.com/lthozo
  email:             leonardo@vertare.com.br

# Custom vars
version:             1.0.0
