# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Leonardo Thozo
tagline:             'Cloud Architect'
description:         'Um blog sobre MS Azure'
url:                 leonardothozo.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Leonardo Thozo
  url:               https://twitter.com/lthozo
  email:             leonardo@vertare.com.br

# Custom vars
version:             1.0.0
